apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
  deployment: sample-app
  template:
    metadata:
      labels:
        deployment: sample-app
    spec:
      containers:
      - name: the-container
        image: quay.io/apoczeka/sample-app:latest
        env:
        - name: APPENV
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: msg
  triggers:
    - type: ConfigChange
